domain: it
required_steps:
  - compliance_type: security_scan
    label: Security Vulnerability Scan
    reason: Required for IT security compliance
    locked: true
  - compliance_type: access_control
    label: Access Control Verification
    reason: Required for access management compliance
    locked: true
  - compliance_type: change_management
    label: Change Management Approval
    reason: Required for IT change control compliance
    locked: true
compliance_rules:
  - ISO 27001
  - SOC 2
  - NIST
  - CIS Controls
stakeholders:
  - user
  - it_admin
  - security_officer
  - change_manager